name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --verbosity normal --configuration Release

      - name: Publish API
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: Your_Function_App_Name
          package: ./publish
          publish-profile: ${{ secrets.AzureWebAppPublishProfile }}
